
start()

def start():
	gcode_file_name = raw_input("Please specify the name of the file with the postfix: ")
	file_object = open(gcode_file_name, "r")
	Z_val = 0

	with file_object as f:
		for line in f:
			eval_line(line)

def eval_line(line):
	# In the gcode file generated by makerbot app, most commands will
	# only have "Z" as a parameter, but be cautious
	if 'Z' in line:
		# get the Z value

	else:
		return -1
