import os
from shutil import copyfile

# get the Z value in the current line
def eval_line(line):
	# In the gcode file generated by makerbot app, most commands will
	# only have "Z" as a parameter, but be cautious
	start = ' Z'
	end = ' F'

	if (start in line) and (end in line):
		# get the Z value
		print(line[line.find(start)+len(start):line.find(end)])
		return float(line[line.find(start)+len(start):line.find(end)])

	else:
		return 0

def has_Z_val(line):
	start = ' Z'
	if start in line:
		return True
	return False

def start():
	gcode_file_name = input("Please specify the name of the file with the postfix: ")
	file_object = open(gcode_file_name, "r")
	file_dst = open("left_half_test_maker_copy.gcode", "w")
	origin_Z = 0
	Z_val = 0
	num_layers_to_insert_gcode = 3
	layers_till_insert = 0;
	file_line_num = 0
	find_init_Z = True
	has_Z = False
	# may need update in the future as gcode become more and more complex
	instrucions_to_insert = "\nM28\n"



	with file_object as f:

		contents = f.readlines()

	with file_dst as fd:
		for i, line in enumerate(contents):
			# obtrain the Z value
			has_Z = has_Z_val(line)
			if has_Z and find_init_Z:
				origin_Z = eval_line(line)
				find_init_Z = False
				pass

			Z_val = eval_line(line)
			dif = Z_val-origin_Z
			if dif == 0 and Z_val != 0:
				origin_Z = Z_val
				pass
			# move up to new layers
			if dif != 0 and Z_val != 0:
				origin_Z = Z_val
				layers_till_insert = layers_till_insert + 1
				if layers_till_insert == num_layers_to_insert_gcode:
					# perform insertion, also be very caustion the line number will also
					# add 1
					layers_till_insert = 0
					# file_line_num = file_line_num + 1
					# now it's time to finally perform insertion
					fd.write(instrucions_to_insert)
					# contents.insert(file_line_num-1)

				# We should insert instruction based on number of layers

		# file_dst.writelines(contents)
		fd.close()
		f.close()

start()


